=== dule2/igraci-nogometnog-kluba-dinamo/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://igraci-dinamo.com/data.json",
    "title": "Igraci Dinama",
    "type": "array",
    "description": "Skup igraca nogometnog kluba Dinamo.",
    "items": {
        "title": "A Schema",
        "type": "object",
        "description": "Objekt koji sadr≈æi sve podatke o jednom igracu.",
        "required": [
            "Ime",
            "Prezime",
            "Broj",
            "Pozicija",
            "Datum_rodenja",
            "Mjesto_rodenja",
            "Visina",
            "Broj_nastupa",
            "Broj_golova",
            "Prosli_klubovi"
        ],
        "properties": {
            "Ime": {
                "title": "Ime",
                "type": "string"
            },
            "Prezime": {
                "title": "Prezime",
                "type": "string"
            },
            "Broj": {
                "title": "Broj",
                "type": "integer"
            },
            "Pozicija": {
                "title": "Pozicija",
                "type": "string"
            },
            "Datum_rodenja": {
                "title": "Datum_rodenja",
                "type": "string"
            },
            "Mjesto_rodenja": {
                "title": "Mjesto_rodenja",
                "type": "string"
            },
            "Visina": {
                "title": "Visina",
                "type": "integer"
            },
            "Broj_nastupa": {
                "title": "Broj_nastupa",
                "type": "integer"
            },
            "Broj_golova": {
                "title": "Broj_golova",
                "type": "integer"
            },
            "Prosli_klubovi": {
                "title": "Prosli_klubovi",
                "type": "array",
                "items": {
                    "title": "Klub",
                    "type": "object",
                    "required": [
                        "Ime_kluba",
                        "Grad_kluba"
                    ],
                    "properties": {
                        "Ime_kluba": {
                            "title": "Ime_kluba",
                            "type": "string"
                        },
                        "Grad_kluba": {
                            "title": "Grad_kluba",
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== dule2/igraci-nogometnog-kluba-dinamo/igraci_nogometnog_kluba_dinamo.json
[{
    "Ime": "Arijan",
    "Prezime": "Ademi",
    "Broj": 5,
    "Pozicija": "vezni",
    "Datum_rodenja": "1991-05-29",
    "Mjesto_rodenja": "Šibenik",
    "Visina": 184,
    "Broj_nastupa": 413,
    "Broj_golova": 47,
    "Prosli_klubovi": [{
            "Ime_kluba": "Šibenik",
            "Grad_kluba": "Šibenik"
        },
        {
            "Ime_kluba": "Lokomotiva",
            "Grad_kluba": "Zagreb"
        }
    ]
}, {
    "Ime": "Raúl",
    "Prezime": "Torrente",
    "Broj": 4,
    "Pozicija": "branič",
    "Datum_rodenja": "2001-09-11",
    "Mjesto_rodenja": "Murcia",
    "Visina": 193,
    "Broj_nastupa": 8,
    "Broj_golova": 2,
    "Prosli_klubovi": [{
        "Ime_kluba": "Granada FC",
        "Grad_kluba": "Granada"
    }]
}, {
    "Ime": "Bruno",
    "Prezime": "Petković",
    "Broj": 9,
    "Pozicija": "napadač",
    "Datum_rodenja": "1994-09-16",
    "Mjesto_rodenja": "Metković",
    "Visina": 193,
    "Broj_nastupa": 265,
    "Broj_golova": 83,
    "Prosli_klubovi": [{
            "Ime_kluba": "Zagreb",
            "Grad_kluba": "Zagreb"
        },
        {
            "Ime_kluba": "Neretva",
            "Grad_kluba": "Neretva"
        },
        {
            "Ime_kluba": "HAŠK",
            "Grad_kluba": "Zagreb"
        },
        {
            "Ime_kluba": "Hrvatski dragovoljac",
            "Grad_kluba": "Zagreb"
        },
        {
            "Ime_kluba": "Catania",
            "Grad_kluba": "Catania"
        },
        {
            "Ime_kluba": "Varese",
            "Grad_kluba": "Varese"
        },
        {
            "Ime_kluba": "Reggiana",
            "Grad_kluba": "Reggio Emilia"
        },
        {
            "Ime_kluba": "Virtus Entella",
            "Grad_kluba": "Chiavari"
        },
        {
            "Ime_kluba": "Trapani",
            "Grad_kluba": "Trapani"
        },
        {
            "Ime_kluba": "Bologna",
            "Grad_kluba": "Bologna"
        },
        {
            "Ime_kluba": "Verona",
            "Grad_kluba": "Verona"
        }
    ]
}, {
    "Ime": "Martin",
    "Prezime": "Baturina",
    "Broj": 10,
    "Pozicija": "vezni",
    "Datum_rodenja": "2003-02-16",
    "Mjesto_rodenja": "Split",
    "Visina": 172,
    "Broj_nastupa": 131,
    "Broj_golova": 18,
    "Prosli_klubovi": [{
        "Ime_kluba": "-",
        "Grad_kluba": "-"
    }]
}, {
    "Ime": "Dario",
    "Prezime": "Špikić",
    "Broj": 77,
    "Pozicija": "napadač",
    "Datum_rodenja": "1999-03-22",
    "Mjesto_rodenja": "Zagreb",
    "Visina": 183,
    "Broj_nastupa": 132,
    "Broj_golova": 18,
    "Prosli_klubovi": [{
            "Ime_kluba": "Hajduk",
            "Grad_kluba": "Split"
        },
        {
            "Ime_kluba": "Gorinca",
            "Grad_kluba": "Velika Gorica"
        }
    ]
}, {
    "Ime": "Sandro",
    "Prezime": "Kulenović",
    "Broj": 17,
    "Pozicija": "napadač",
    "Datum_rodenja": "1999-12-04",
    "Mjesto_rodenja": "Zagreb",
    "Visina": 191,
    "Broj_nastupa": 67,
    "Broj_golova": 20,
    "Prosli_klubovi": [{
            "Ime_kluba": "Legia Warsaw",
            "Grad_kluba": "Warsaw"
        },
        {
            "Ime_kluba": "Rijeka",
            "Grad_kluba": "Rijeka"
        },
        {
            "Ime_kluba": "Juventus U19",
            "Grad_kluba": "Turin"
        }
    ]
}, {
    "Ime": "Kevin",
    "Prezime": "Teophile-Catherine",
    "Broj": 28,
    "Pozicija": "branič",
    "Datum_rodenja": "1989-10-28",
    "Mjesto_rodenja": "Saint-Brieuc",
    "Visina": 183,
    "Broj_nastupa": 191,
    "Broj_golova": 4,
    "Prosli_klubovi": [{
            "Ime_kluba": "Rennes",
            "Grad_kluba": "Rennes"
        },
        {
            "Ime_kluba": "Cardiff City",
            "Grad_kluba": "Cardiff"
        },
        {
            "Ime_kluba": "Saint-Étienne",
            "Grad_kluba": "Saint-Étienne"
        }
    ]
}, {
    "Ime": "Ivan",
    "Prezime": "Nevistić",
    "Broj": 33,
    "Pozicija": "vratar",
    "Datum_rodenja": "1998-07-31",
    "Mjesto_rodenja": "Đakovo",
    "Visina": 193,
    "Broj_nastupa": 48,
    "Broj_golova": 0,
    "Prosli_klubovi": [{
            "Ime_kluba": "Rijeka",
            "Grad_kluba": "Rijeka"
        },
        {
            "Ime_kluba": "Varaždin",
            "Grad_kluba": "Varaždin"
        },
        {
            "Ime_kluba": "NŠ Mura",
            "Grad_kluba": "Murska Sobota"
        },
        {
            "Ime_kluba": "Osijek",
            "Grad_kluba": "Osijek"
        }
    ]
}, {
    "Ime": "Petar",
    "Prezime": "Sučić",
    "Broj": 25,
    "Pozicija": "vezni",
    "Datum_rodenja": "2003-10-25",
    "Mjesto_rodenja": "Livno",
    "Visina": 183,
    "Broj_nastupa": 56,
    "Broj_golova": 3,
    "Prosli_klubovi": [{
        "Ime_kluba": "-",
        "Grad_kluba": "-"
    }]
}, {
    "Ime": "Josip",
    "Prezime": "Mišić",
    "Broj": 27,
    "Pozicija": "vezni",
    "Datum_rodenja": "1994-06-28",
    "Mjesto_rodenja": "Vinkovci",
    "Visina": 187,
    "Broj_nastupa": 187,
    "Broj_golova": 6,
    "Prosli_klubovi": [{
            "Ime_kluba": "Osijek",
            "Grad_kluba": "Osijek"
        },
        {
            "Ime_kluba": "Rijeka",
            "Grad_kluba": "Rijeka"
        },
        {
            "Ime_kluba": "Spezia",
            "Grad_kluba": "La Spezia"
        },
        {
            "Ime_kluba": "Sporting",
            "Grad_kluba": "Lisbon"
        },
        {
            "Ime_kluba": "PAOK",
            "Grad_kluba": "Thessaloniki"
        }
    ]
}, {
    "Ime": "Maxime",
    "Prezime": "Bernauer",
    "Broj": 6,
    "Pozicija": "branič",
    "Datum_rodenja": "1998-07-01",
    "Mjesto_rodenja": "Hennebont",
    "Visina": 186,
    "Broj_nastupa": 33,
    "Broj_golova": 2,
    "Prosli_klubovi": [{
            "Ime_kluba": "Rennes",
            "Grad_kluba": "Rennes"
        },
        {
            "Ime_kluba": "Concarneau",
            "Grad_kluba": "Concarneau"
        },
        {
            "Ime_kluba": "Le Mans FC",
            "Grad_kluba": "Le Mans"
        },
        {
            "Ime_kluba": "Paris FC ",
            "Grad_kluba": "Paris"
        }
    ]
}]
